CREATE DATABASE IF NOT EXISTS grupo180_crm;
USE grupo180_crm;

CREATE TABLE IF NOT EXISTS leads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    source VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'nuevos',
    date DATETIME DEFAULT CURRENT_TIMESTAMP
);
